name: Execução pipeline - Push

on:
  push:
    branches: [ "main", "master" ]

  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm run test:file

    - name: Debug reports
      run: ls -R reports || echo "sem report"

    - name: Upload HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jest-report
        path: reports/

    - name: Deploy report
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
